### PR TITLE
Fixed building with zig master 0.16.0-dev.1593+c13857e50

### PR DESCRIPTION
**Pull request by dtasada**
fixed deprecated error codes, as well as deprecated Io interface in examples when building with zig 0.16.0-dev.1593+c13857e50. also merged master into zig-master.

### CODE REVIEW

**Comment by ikskuh** [comment]
Can you rebase this PR onto latest `master` branch of this repo?

**Comment by dtasada** [comment]
`zig-master` is now merged with `master`.

**Comment by dtasada** [comment]
i rebased `master` into `dtasada:zig-master`.

**Comment by dtasada** [comment]
i saw the CI failed on this PR. i can personally confirm all examples compile on 0.16.0-dev.1593+c13857e50 (on macos), but i don't know how the CI is set up and what zig version it uses.

**Comment by ikskuh** [comment]
> i saw the CI failed on this PR. i can personally confirm all examples compile on 0.16.0-dev.1593+c13857e50 (on macos), but i don't know how the CI is set up and what zig version it uses.


```
network.zig:1465:38: error: root source file struct 'std' has no member named 'net'
        const address_list = try std.net.getAddressList(allocator, name, port);
                                     ^~~
/home/runner/work/_temp/186dd26c-4cb7-40f4-9574-c54e4348a0af/zig-x86_64-linux-0.16.0-dev.1657+985a3565c/lib/std/std.zig:1:1: note: struct declared here
```

Your 64 commits behind master, someone deleted `std.net` :rofl:
